conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  root:  ./data/imagenet11/

measurement:
  operator:
    name: high_dynamic_range
    scale: 2
    sigma: 0.05

  noise: 
    name: gaussian
    sigma: 0.05
