conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  #root: ./data/demo/
  root:  ./data/imagenet5/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    #mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.7, 0.71]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
    #sigma: 0.05
