conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: ffhq
  root:  ./data/imagenet13/
  #root: ./data/ffhq_demo/
  #root: ./data/demo/
  #root: ./data/ffhq6/
measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0

  noise: 
    name: gaussian
    sigma: 0.05
